name: flutter_class_1
description: Flutter class Modular, Clean architecture e Mobx

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mobx: 2.0.5
  flutter_mobx: 2.0.2
  flutter_modular: 3.3.1

dev_dependencies:
  flutter_modular_test: 1.0.1
  flutter_test:
    sdk: flutter
  mobx_codegen: 2.0.2
  modular_codegen: 3.0.2
  build_runner: 2.1.2

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
vars:
  get: flutter pub get
  build: flutter pub run build_runner

scripts:
  build_runner: $get && $build build --delete-conflicting-outputs
  watch_runner: $get && $build watch --delete-conflicting-outputs
